apiVersion: v1
kind: Service
metadata:
  name: student-portal-frontend
  namespace: student-portal
spec:
  type: ClusterIP
  selector:
    app: student-portal-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
