apiVersion: v1
kind: ConfigMap
metadata:
  name: student-portal-config
  namespace: student-portal
data:
  PORT: "5000"
  NODE_ENV: "production"

  # MySQL (RDS)
  DB_HOST: "portal-db.cwhdtq5zkyxh.us-east-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_USER: "admin"
  DB_NAME: "student_app"

  JWT_EXPIRE: "15d"

  # CORS - use your public domain (recommended)
  FRONTEND_URL: "http://arsene-student-portal.duckdns.org"
