apiVersion: v1
kind: Service
metadata:
  name: student-portal-backend
  namespace: student-portal
spec:
  type: ClusterIP
  selector:
    app: student-portal-backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
