{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: student-portal-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.clusterIssuer }}
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.tls.clusterIssuer }}"
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.global.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-portal-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: student-portal-backend
                port:
                  number: 5000
{{- end }}
